accounts:
- account: admin
  password: "123456"
connections:
- servicename: localhost
  host: 127.0.0.1
  port: "6379"
  password: ""
  usessh: 0
  sshconfig:
    sshhost: ""
    sshport: ""
    sshusername: ""
    sshpassword: ""
mysql_config:
- servicename: localhost
  host: localhost
  port: "3306"
  username: "root"
  password: "root"
  database: "go-db"
hostname: 127.0.0.1
limit: 20
port: "8088"
